spring:
  application:
    name: bbs-app
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: postgres
    jmx:
      default-domain: bbs-app
server:
  servlet:
    context-path: /bbs-app